### ISSUE TITLE
Python package dependency issue

### ISSUE THREAD

**Issue by calebhallinan** [joshlk/k-means-constrained#21]
Hello! I was hoping to use your package on k-means-constrained in order to get equal cluster sizes. However, I have run into the issue where different python packages need different versions. Your package requires numpy >1.22, however numba (which is in the umap package) requires numpy <=1.21. Hence, if I would like to cluster data from umap, I am unable to do so with your package due to the numpy version requirement.

With the latest update, numba can only use numpy <=1.21 so I can't upgrade it any further.

Do you happen to know a way around this?

Thanks!

**Comment by joshlk** [comment]
Hi, great to hear your using the package 🙂. One way around it would be to use `k-means-constrained==0.6.0` which works with `numpy==1.20.3`. Another way is to clone this repo and build and install the package from source with any numpy version. If the first method doesn’t work I can provide you details on how to do it

**Comment by arogozhnikov** [comment]
Unfortunately, neither combination of numpy and k-means-constrained works for me.

Tried 0.6.0 and numpy 1.20.* and numpy 1.20.3
Tried 0.7.0 and numpy 1.21.* and numpy 1.21.5

Tried building with --no-binary.

Can't use 1.22 because of numba. Even more surprising to me that a couple of months ago I've managed to get 0.6.0 to work, but I don't remember which numpy version I've installed 😕

**Comment by alfredostrath** [comment]
Hi! I'm dealing with the same issues mentioned above and would be grateful for any info on how to solve it. Thank you :)

**Comment by joshlk** [comment]
This is an unfortunate reality of Pythons packaging system - you can't get out of dependency hell. I'm closing this for now.
