### ISSUE TITLE
Wrong clustering with pre_computed adjacency matrix

### ISSUE THREAD

**Issue by mosikh** [joshlk/k-means-constrained#35]
Hello,
I used k-means-constrained library to cluster some points with a precomputed adjacency matrix. But I faced a wrong clustering. 
The project and further explanations are available in this link. 

https://github.com/mosikh/k-means-constrained

I appreciate any help to improve the result.

Best regards,
Mostafa

**Comment by joshlk** [comment]
Hi Mostafa,

Thank you for the example. I wouldn’t consider the provided example a minimum workable example. [Stackoverflow have a good article on how to produce this](https://stackoverflow.com/help/minimal-reproducible-example). Importantly the example should contain the least amount of code and data to reproduce the result you want to present. Ideally you should be able to paste it as few lines of code and include only a few datapoints of data within a GitHub comment.

I also don’t understand the problem? Why is the desired output not what you expected and why should the algorithm not give this output?

I know the above is more difficult to produce but it really helps me understand the issue. Otherwise it’s very hard for me to debug it 🙂

Thanks,
Josh
