### ISSUE TITLE
conda version

### ISSUE THREAD

**Issue by drcandacemakedamoore** [joshlk/k-means-constrained#56]
Dear coders, I noticed you have no conda version, which I would need to properly package something I have where this is a dependency. I will therefore ask to add your code in my library as a temporary fix, with the license and README of course. My code is here:  https://github.com/brainspinner/cvasl , and there is a vendor folder with outside code.

**Comment by joshlk** [comment]
Hi, great to hear you are using the package and thanks for letting me know you are embedding the library into your repo 😃

**Comment by joshlk** [comment]
Out of interest, how are you using k-means-constrained in your project?

**Comment by brainspinner** [comment]
Hi, I am using your project because it is a dependency of a neuroimaging harmonization library. Unfortunately, most of these libraries were never released and versioned in any form, so I had to do a "vendor" version of them, now available [here https://github.com/brainspinner/cvasl . ](here: https://github.com/brainspinner/cvasl ,) as of a few days ago. Sometimes the dependiencies absolutely need a specific version of a library like yours to work correctly; but here the issue is that I want to keep everything a conda package, so to [ackage things correctly the way I know how, I would need to either have a conda version of your package, or vendor a part of your package (I'll add a lisence and credit you). Thanks!
